### ISSUE TITLE
Problem running multiple boxes with different host folders

### ISSUE THREAD

**Issue by d-Metrius** [winnfsd/vagrant-winnfsd#10]
When I make "vagrant up" in my second project folder all the mounts in both boxes mess up. Thus I cannot run multiple boxes at the same time.

At first I thought, that this is because of the same SSH port both boxes use, but then I've changed it to different one in second box. Now it's clear to me, that I have only one running instance of winnfsd with one "nfspaths" file (projcect1) and when I start second box, it changes this instance somehow.

**Comment by DZunke** [comment]
the problem still exists, is there any known way for a workaround? have tried to google for this but didn't found a solution. it would be nice if this is fixed but if someone know a workaround i would be gratefull :smile:

**Comment by worthwhileindustries** [comment]
@DZunke I think this is a problem with WinNFS. We need to talk to those guys I think.

**Comment by bate** [comment]
Is this version used right now?

https://bitbucket.org/jankowfsky/winnfsd

**Comment by worthwhileindustries** [comment]
@bate or this one

https://bitbucket.org/yannschepens/winnfsd 

?

**Comment by GM-Alex** [comment]
Ok seems there is some confusion. Used is https://bitbucket.org/jankowfsky/winnfsd which contains all changes from https://bitbucket.org/yannschepens/winnfsd. Because the fork of winnfsd, at https://bitbucket.org/jankowfsky/winnfsd, is also my project like vagrant-winnfsd and Yann made some really good pull requests, I invited Yann to be part of the winnfsd project and he agreed. So the newest version of winnfsd will be always at https://bitbucket.org/jankowfsky/winnfsd

**Comment by ngreen30** [comment]
Also seeing this issue on Windows 7 host with an ubuntu multi machine setup. First box boots and shares correctly - second one hits the error already described above -

[NFS] Status: running
==> miproject: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp,nolock' 192.168.55.1:'/C/<SHARE_FILE_PATH_HERE>' /var/www/wd_miproject

Stdout from the command:


Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 192.168.55.1:/C/<SHARE_FILE_PATH_HERE>


Running Vagrant 1.6.3, with vagrant-winnfsd (1.0.11)

Any ideas for a workaround?

**Comment by ngreen30** [comment]
Found the workaround in the related issue:

https://github.com/GM-Alex/vagrant-winnfsd/issues/12

The problem is a bug with winnfsd. It relates to the length of the path you are sharing, set up your shares in length ascending order and all appears to work correctly.

**Comment by ngaller** [comment]
I had the same thing - first machine boots and loads shared folders fine but the second one gets:

    mount.nfs: access denied by server while mounting 192.168.55.1:/C/HOST_SHARE_PATH_HERE

However once I kill winnfsd and reload the VM it works fine.  What happened is winnfsd was only started the first time, when the second VM booted it edited the winnfsd configuration but saw it was already running so didn't restart it.  On subsequent boots the folders were already defined as shared so it worked without needing to kill winnfsd.  The shared folders are stored in C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\nfspaths, if you need to review / edit them.

**Comment by mablae** [comment]
@nicocrm I am running into the same issue, but it seems every boot of a VM now replaces all entries in 
the nfs shares every time? 

Why is this all so hard?

**Comment by adsc-cloudtec** [comment]
@nicocrm and @mablae are right, you CAN switch machine by halting the old one, killing winnfsd and upping the new one, but you CAN'T run two machines at the same time with different shares. The shares are always replaced, which means that the old machine will have the same mounts as the new one.

**Comment by marcharding** [comment]
Since v1.2.1 you can run multiple vm side by side.

**Comment by adsc-cloudtec** [comment]
@marcharding Great news, thanks a lot!
