### ISSUE TITLE
403 Permission denied errors when using nfs

### ISSUE THREAD

**Issue by morcth** [winnfsd/vagrant-winnfsd#115]
Hello,

I am getting 403 errors on all css and js files when I turn on NFS after installing the plugin. This is a win 10 x64 machine. The exact same vagrant file and htaccess files and everything else works fine on a win 7 pro machine. Pasting the inspector error below. There are a few of these for css and js files so the site does not work at all. It works fine with nfs off. 

Any ideas?

GET http://192.168.33.10/sites/default/files/css/css_1UAsYyAX13183hXi-xugrKf3oj0cavSEJHmskYFyD94.css net::ERR_ABORTED

Thanks,
Josh

**Comment by GM-Alex** [comment]
Have you tried to set the right uid or gid?

**Comment by morcth** [comment]
Hi Alex,

I have not. Can you point me in the right direction to find out more about the variables? I see I can set them using winnfsd but I have no idea what to change them to.

Thanks!

**Comment by GM-Alex** [comment]
Start your vagrant without winnfsd and go to the dir where are the files you want to mount located. Than type `ls -la`which should show you a list of the files including the permissions and the users and groups of the files. I think it could be `apache` or `www-data` in your case. Then type `id -u USERNAME` and `id -g GROUPNAME` to get the uid and the gid. Set this in your vagrant file and test again.

**Comment by morcth** [comment]
Hey Alex,

I did what you said and still wasn't working. It made no sense as all other files had the same id, gid and permissions. So I deleted the entire project and set it all up again and it worked fine. Maybe it had something with how I cloned the repository... who know. It is working now though.

Thanks for your time.

Josh
