### ISSUE TITLE
Error: conflicting dependencies ffi

### ISSUE THREAD

**Issue by val7000** [winnfsd/vagrant-winnfsd#120]
Hello

Trying to install on Windows 7 by `vagrant plugin install vagrant-winnfsd`

Getting error:

![default](https://user-images.githubusercontent.com/1336299/36792774-8d259866-1cac-11e8-9eeb-f065e57fd954.png)

Upgraded Vagrant to latest 2.0.2. Still the same.

**Comment by 3manuek** [comment]
I'm having the same issue on MacOs, couldn't figure out yet how to fix this.

**Comment by val7000** [comment]
@3manuek thanks! it helps
