### ISSUE TITLE
What permissions are required in Windows 10?

### ISSUE THREAD

**Issue by D41161195** [winnfsd/vagrant-winnfsd#137]
I am attempting to set up our company local dev environment on my Windows 10 laptop.  I have to get company IT to install applications that require elevated access or permissions.   Now that Vagrant is installed, I am able to install this plug-in myself.  However, now when I run `vagrant up` I get a series of prompts for elevated access. 

What permissions are needed in order to set up the NFS on Win10 using this plug-in?  IT will, if required, grant me some granular permissions if they know what to grant.

**Comment by pgrafe** [comment]
The plugin wants to add a firewall rule for winnfsd.exe. The call for adding this rule can be found in this file:

https://github.com/winnfsd/vagrant-winnfsd/blob/master/lib/vagrant-winnfsd/plugin.rb

Hope this helps.

**Comment by D41161195** [comment]
Thanks!  I finally prevailed and they gave me a Mac.   I'm sure someone will benefit from this.
