### ISSUE TITLE
Issue installing JSON gem on Windows 7

### ISSUE THREAD

**Issue by JaTochNietDan** [winnfsd/vagrant-winnfsd#19]
I run the installation command for this plugin in the root folder of my project and I get an error saying the following:

```
Installing the 'vagrant-winnfsd' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.
```

So then I run the command as it suggests and low and behold...it seemingly succeeds and the gem has been installed. Then upon running the command to install this plugin, I get the same error again. I can't figure out what's wrong here.

**Comment by wowpatrick** [comment]
Thanks @thinkrapido! Your solution also worked fine for me on Windows 7.
