### ISSUE TITLE
Permission denied with temporary file created by "sed -i"

### ISSUE THREAD

**Issue by lukey78** [winnfsd/vagrant-winnfsd#21]
Hi there,

does anyone have a similar issue in a NFS shared folder?

```
echo testdata>test.dat
sed -i "s/testdata/blabla/g" test.dat
=> sed: couldn't close ./sedJET6DQ: Permission denied
```

Output from NFS log file:

```
NFS GETATTR C:\entwicklung\projekte\kmu\test.dat  OK
NFS ACCESS C:\entwicklung\projekte\kmu\test.dat  OK
NFS CREATE C:\entwicklung\projekte\kmu\sedJET6DQ  OK
NFS SETATTR C:\entwicklung\projekte\kmu\sedJET6DQ  OK
NFS WRITE C:\entwicklung\projekte\kmu\sedJET6DQ Permission denied ACCESS
```

The linux user (tried also with root) can create, read and update any files in the NFS mounted folder. But the temporary file created by sed doesn't work.

Can anyone confirm this behaviour?

Thanks!
Jens

**Comment by zanglinjie** [comment]
Has the problem been solved？？

**Comment by zanglinjie** [comment]
> Hi there,
> 
> does anyone have a similar issue in a NFS shared folder?
> 
> ```
> echo testdata>test.dat
> sed -i "s/testdata/blabla/g" test.dat
> => sed: couldn't close ./sedJET6DQ: Permission denied
> ```
> 
> Output from NFS log file:
> 
> ```
> NFS GETATTR C:\entwicklung\projekte\kmu\test.dat  OK
> NFS ACCESS C:\entwicklung\projekte\kmu\test.dat  OK
> NFS CREATE C:\entwicklung\projekte\kmu\sedJET6DQ  OK
> NFS SETATTR C:\entwicklung\projekte\kmu\sedJET6DQ  OK
> NFS WRITE C:\entwicklung\projekte\kmu\sedJET6DQ Permission denied ACCESS
> ```
> 
> The linux user (tried also with root) can create, read and update any files in the NFS mounted folder. But the temporary file created by sed doesn't work.
> 
> Can anyone confirm this behaviour?
> 
> Thanks!
> Jens

Has the problem been solved
