### ISSUE TITLE
mount system call failed

### ISSUE THREAD

**Issue by rdpascua** [winnfsd/vagrant-winnfsd#47]
I'm using Homestead on Windows 8.1 Hosts,

I got this error whenever I executed `vagrant up`, this doesn't mount my folder of course.
Anyone got this issue? 

```
==> default: Mounting NFS shared folders...                           
The following SSH command responded with a non-zero exit status.      
Vagrant assumes that this means the command failed!                   

mount -o 'actimeo=1' 192.168.10.1:'/D/projects' /home/vagrant/Code    

Stdout from the command:                                                                                                                                         

Stderr from the command:                                              

mount.nfs: mount system call failed                                   
```

**Comment by rdpascua** [comment]
I did try to modify `homestead.rb` checked the nfs settings changed the following:

```
mount_opts = folder["type"] == "nfs" ? ['actimeo=1'] : []
```

to 

```
mount_opts = folder["type"] == "nfs" ? ['nolock,vers=3,udp,noatime'] : []
```

Anyhow I don't see any performance when doing large projects.

**Comment by rdpascua** [comment]
I can only write guest-to-host, damn.

**Comment by rdpascua** [comment]
Returning the `actimeo=1`, allows editing again. but having issues with git adding new files
```
mount_opts = folder["type"] == "nfs" ? ['nolock,vers=3,udp,noatime,actimeo=1'] : []
```

throws the following:

```
fatal: error when closing sha1 file: Permission denied
```

**Comment by ingro** [comment]
Got the exact same error, except that I'm running Windows 7 x64

**Comment by rdpascua** [comment]
Well I can't really work with disabled nfs, its takes time to load everything. I might switch back to ubuntu if this issue persists, really kills my productivity

**Comment by ingro** [comment]
I used your workaround in `homestead.rb` to mount the nfs folders and a dev version of winnfsd to avoid the "permission denied" error, Now the performance are slightly better than standard shared folder, but I guess it's better than nothing!

**Comment by rdpascua** [comment]
How did you use the dev version ?

**Comment by ingro** [comment]
I found the updated `winnfsd.exe` [here](https://bitbucket.org/jankowfsky/winnfsd/issue/9/rename-file-on-vm-does-not-work-previously#comment-17261362), then I overwrite the old one in `C:\Users\YourUser\.vagrant.d\gems\gems\vagrant-winnfsd-1.0.11\bin`

**Comment by yannschepens** [comment]
Hello,

For information, there is a new development winnfsd release :
https://bitbucket.org/jankowfsky/winnfsd/issue/9/rename-file-on-vm-does-not-work-previously#comment-17848958

2015-05-13 15:46 GMT+02:00 Emanuele Ingrosso <notifications@github.com>:

> I found the updated winnfsd.exe here
> <https://bitbucket.org/jankowfsky/winnfsd/issue/9/rename-file-on-vm-does-not-work-previously#comment-17261362>,
> then I overwrite the old one in
> C:\Users\YourUser\.vagrant.d\gems\gems\vagrant-winnfsd-1.0.11\bin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/47#issuecomment-101668552>
> .
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by ingro** [comment]
Thanks @yannschepens , I will give it a try as soon as I can!

**Comment by rdpascua** [comment]
Thanks will notify if it works

**Comment by rdpascua** [comment]
Well it works, but git commands doesn't work anymore? leaves the terminal frozen
