### ISSUE TITLE
Slow copy files when using nfs with windows host and ubuntu guest

### ISSUE THREAD

**Issue by mbury** [winnfsd/vagrant-winnfsd#52]
I have very strange performance issue when I mount shared folders using nfs and vagrant-winnfsd plugin. In my project I have grunt task which copy 120 javascript  files and I use it to show my problem.
I start copy task at 3 different configuration. 

My VPS with native Ubuntu:
![native](https://cloud.githubusercontent.com/assets/1153346/7257419/d966c7d8-e855-11e4-83ec-20a460a44120.PNG)
Windows host and Ubuntu guest with default shared folder:
![default](https://cloud.githubusercontent.com/assets/1153346/7257418/d9656f8c-e855-11e4-8629-478bfce5f71d.PNG)
Windows host and Ubuntu guest with **nfs** and vagrant-winnfsd plugin:
![nfs](https://cloud.githubusercontent.com/assets/1153346/7257420/d9674974-e855-11e4-8351-b153370cda58.PNG)

Can someone tell me explain me why simple copy files command take so much time? I miss something in configuration? When I search information about nfs share folders everyone say that setting is much more faster in read write data.

My current setting is:
Host: Windows 7 x64, VirtualBox 4.3.26, Vagrant 1.7.2, vagrant-winnfsd 1.0.11
Guest: Ubuntu 14.04 x64

**Comment by GM-Alex** [comment]
See the following entry for more informations about the performance: https://github.com/GM-Alex/vagrant-winnfsd/wiki/Benchmarking-winnfsd-vs-VirtualBox-Shared-Folders
