### ISSUE TITLE
2GB file size limit

### ISSUE THREAD

**Issue by majidaldo** [winnfsd/vagrant-winnfsd#55]
i can't access files more than 2GB in size. nfs v3 is supposed to not have a 2GB file limit but i suspect the problem is coming from the fact that winnfsd is a 32bit exe.

Does anyone have a 64bit compiled version? Is this this the problem?

Guest: CoreOS
Host win 8.1 (64)
latest vagrant

**Comment by JohnByrne** [comment]
Also having this issue

**Comment by marcharding** [comment]
Fixed with v1.2.0.
