### ISSUE TITLE
Weird issue on freebsd guest

### ISSUE THREAD

**Issue by krzysztofantczak** [winnfsd/vagrant-winnfsd#56]
I'm mounting local project (from host) to /var/www (on guest), using following code (actually default vagrant directory also doesn't work):

```
config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"], :nfs => true
```

Now on host (windows):
```
echo "test" > foo
```

And the result on guest (freebsd) is:
```
% ls /var/ww
% cat /var/www/foo
test
```

So files are there! Sync works fine in both directions but:
1. i'm unable to see those files/directories using unix commands
2. when i put nginx vhost in my project directory, nginx also can't see it

Also, there is no indication of any error on both sides - nothing in logs, nothing weird in vagrant output.

Any ideas?

**Comment by marcharding** [comment]
I'm closing this issue, please see https://github.com/winnfsd/vagrant-winnfsd/issues/78 for a proposed solution and a fixed exe.
