### ISSUE TITLE
mklink and symlink

### ISSUE THREAD

**Issue by HnLn** [winnfsd/vagrant-winnfsd#69]
I just discovered that my win10 has a mklink functionality (command line).  Seems to work pretty much like a linux symlink, it's not a shortcut but actually shows the files within the folder.

Is it possible that such links get translated to symlinks on the guest system ?  Of course this would be only possible if the linked folder is with the mounted nfs share.  For the moment my vagrant box (ubuntu) seems to recognize the mklink as a symbolic link (it has a little arrow next to it's name, but nothing next to the arrow).  I can cd into the directoty but it points to the parent dir.

I guess this is quite difficult or even impossible, but no harm in asking :-).

**Comment by kadet1090** [comment]
Yes, it even works ;) Just run winnfsd as admin and voila.

**Comment by HnLn** [comment]
Ok I had it working on a test directory, using /d as the mklink parameter, but now I try it on my working dirs and winnfsd crashes.  I tried with /j before, and that doesn't work (the symbolic link in my guest ubuntu just points to itself).  What parameters do you use for the mklink command ?

**Comment by HnLn** [comment]
Ok, i know why I had it working on a test directory, the relative path was only 1 level down ../foo.  When I create a windows symbolic link that is more then one level down (the one I want is actually 4 levels down), like mklink /d foo ..\..\..\..\foo, winnfsd crashes when I access that directory.

**Comment by kadet1090** [comment]
First of all you should do ..\..\..\..\foo rather than ........\foo. And i'm not sure if winnfsd is capable of serving files from outside of shared directory, but it should if on one level deep it works well. And remember that even if you could symlink to things on your nfs client (vagrant guest) you won't be able to access them on your host.

**Comment by HnLn** [comment]
yeah my slashes got stripped out :-)

The linked directory is still within the nfs share.

**Comment by kadet1090** [comment]
Hmm, have you turned on winnfsd logging? It would be really helpful.

**Comment by HnLn** [comment]
see also https://github.com/winnfsd/winnfsd/issues/10

(trying to get some logging going)

**Comment by HnLn** [comment]
First image is the crash, a makelink that goes down 2 (or more) levels.  Second image works ok, a makelink that goes down one level.  The crash happens the moment you try to access the directory (either from console, e.g. ls -l or also when accessing it from a webserver).

![winnfsd_crash](https://cloud.githubusercontent.com/assets/5806950/10454715/150054ae-71b7-11e5-9b2a-874aed1602ce.png)
![winnfsd_no_crash](https://cloud.githubusercontent.com/assets/5806950/10454723/1c1d200a-71b7-11e5-98d5-f6f694a5a7cb.png)

**Comment by marcharding** [comment]
Symlinks should be fixed with v1.2.0. 

Symlinks must point somewhere in the mount, you cannot symlink into the native guest file system.
