### ISSUE TITLE
NFS v4 support

### ISSUE THREAD

**Issue by aistis-** [winnfsd/vagrant-winnfsd#71]
Hello guys, does the lib support NFS v4? Is it planned to be supported?

**Comment by aistis-** [comment]
Nevermind. It seems winnfs supports only v3 http://winnfsd.sourceforge.net/

**Comment by worthwhileindustries** [comment]
@aistis- I don't think that is the exact version we are using here. you'll have to look around posts... there's a github repo that winnfsd is from
