### ISSUE TITLE
WinNFSd can't open file Vagrant/embedded/gems/gems/vagrant-X.Y.Z/nfspaths

### ISSUE THREAD

**Issue by ferenczy** [winnfsd/vagrant-winnfsd#73]
I have successfully installed the `vagrant-winnfsd` plugin:

    vagrant plugin install vagrant-winnfsd

While Vagrant is executing a VM using `vagrant up`, new Windows console window containing this error is opened:

    Can't open file C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.7.4/nfspaths.

    Current directory:
    D:\vagrant\development

    Command to be executed:
    "C:\Users\ferenczy\.vagrant.d\gems\gems\vagrant-winnfsd-1.1.0\bin\winnfsd.exe" -log off -pathFile "C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.7.4/nfspaths" -id 0 0

...and `vagrant up` hangs on `Mounting NFS shared folders...` for some time, then it time outs.

The file `C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.7.4/nfspaths` really **doesn't exists** (but the directory `vagrant-1.7.4` does).

My synced folder configuration in `Vagrantfile` looks like this:

    config.vm.synced_folder "../sources", "/work",
        :id => 'work-root',
        :type => 'nfs',
        :mount_options => ['nolock,vers=3,udp,noatime']

...and it's the only synced folder configured. It works fine with VirtualBox's shared folders.

I'm using *Windows 7 64 bit* host, *Ubuntu 14.04.3* guest, *Vagrant 1.7.4* and *VirtualBox 5.0.0*.

What am I missing?

**Comment by GM-Alex** [comment]
It seems that the nfspaths file is not readable or not created. Does the file exists? It could be some permission problem.

**Comment by caio2k** [comment]
I had this problem also. Solved by reinstalling Vagrant in default folder C:\Hashicorp\Vagrant. I suspect there is an issue with folder name with spaces.

**Comment by marcharding** [comment]
This is fixed since 1.2.1.
