### ISSUE TITLE
winnfsd.exe crashes often can't find the reason

### ISSUE THREAD

**Issue by rgrimm-neom** [winnfsd/vagrant-winnfsd#76]
Winnfsd crashes a lot for me, leaving my vagrant box with an unusable mount point. After reloading vagrant it works for some time. I tried debugging by using the winnfsd log but the logging window closes before I can see what the problem was.

Is there a log file somewhere? I can't find one.

The problem seems to occur when winnfsd is under heavy load, but on other times the same load seems to be no problem.

**Comment by rgrimm-neom** [comment]
Reloading vagrant doesn't help either, since the problem will reoccur as soon as I try to load a web page once it occured the first time.

**Comment by rgrimm-neom** [comment]
Maybe this is related to #68 .

**Comment by marcharding** [comment]
That should be fixed by now.
