### ISSUE TITLE
Cannot install plugin - Windows 7 x64

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [winnfsd/vagrant-winnfsd#92]
Oddly enough I haven't had this issue before today. NFS became extremely slow so I decided to clear out the plugin and reinstall.

My attempt to uninstall via the `vagrant plugin` command failed as it told me that the plugin wasn't installed - even though it was. So I deleted all traces of winnfsd in the `vagrant.d` folder and then nuked the json file and reinstalled all plugins.

Then I came across this error:

```
I:\>vagrant plugin install vagrant-winffsd
Installing the 'vagrant-winffsd' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins, reported an error. The error is shown below. These errors are usually caused by misconfigured plugin installations or transient network issues. The error from Bundler is:

Could not find gem 'vagrant-winffsd x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
```

Windows is host, Ubuntu is guest.

**Comment by marcharding** [comment]
vagrant-winnfsd not vagrant-winn**f**fsd :wink:

**Comment by JakeTheSnake3p0** [comment]
Doh! Thanks

**Comment by rintoug** [comment]
I have installed as separate console  vagrant plugin install vagrant-winnfsd

It works
