### ISSUE TITLE
Issue with a symlinks

### ISSUE THREAD

**Issue by andrvin** [winnfsd/vagrant-winnfsd#95]
Hi guys! Thank you for your work! But why I can't create a symlink on the nfs mounted system on my vagrant VirtualBox machine? I got this error when I tried:
ln: failed to create symbolic link ‘/bla/bla/file’: Input/output error

**Comment by marcharding** [comment]
Do you run vagrant as administrator? Unfortunately symlinks on windows only work as administrator...

If that does not fix it: Whats you plugin version (`vagrant plugin list`) and what exact command did you execute (`ln -s foo bar`).

**Comment by andrvin** [comment]
Thank you! It solves the problem! But I have another question how I can run winnfsd with async option(if it is possible)?

**Comment by marcharding** [comment]
I'm working on it, take a look here https://github.com/winnfsd/winnfsd/issues/22#issuecomment-230125433

I'm closing this issue, because the symlink issue is resolved.

**Comment by QzeroQ** [comment]
The version I use is: vagrant-winnfsd (1.4.0)
The command I execute is : tail -f  lum-180622.log
The error message is: reverting to polling: Input/output error
Please help me, thank you@marcharding
